import { prisma } from "../db/prisma.ts";

async function seedCars() {
  await prisma.$executeRawUnsafe('TRUNCATE "Car" RESTART IDENTITY;');

  const result = await prisma.car.createMany({
    data: [
      {
        imageUrl: "/208.png",
        brand: "Peugeot",
        model: "208",
        year: 2022,
        vehicleType: "SEDAN",
        category: "ECONOMY",
        pricePerDay: 2947,
        seats: 5,
        bagCapacity: 2,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 28,
      },
      {
        imageUrl: "/fiat-cronos.png",
        brand: "Fiat",
        model: "Cronos",
        year: 2023,
        vehicleType: "SEDAN",
        category: "ECONOMY",
        pricePerDay: 3180,
        seats: 5,
        bagCapacity: 2,
        suitcaseCapacity: 1,
        gearbox: "MANUAL",
        ageRequired: 21,
      },
      {
        imageUrl: "/onix-plus.png",
        brand: "Chevrolet",
        model: "Onix Plus",
        year: 2022,
        vehicleType: "SEDAN",
        category: "ECONOMY",
        pricePerDay: 3050,
        seats: 5,
        bagCapacity: 2,
        suitcaseCapacity: 1,
        gearbox: "MANUAL",
        ageRequired: 21,
      },
      {
        imageUrl: "/corolla.webp",
        brand: "Toyota",
        model: "Corolla",
        year: 2023,
        vehicleType: "SEDAN",
        category: "PREMIUM",
        pricePerDay: 5400,
        seats: 5,
        bagCapacity: 2,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 25,
      },
      {
        brand: "Volkswagen",
        model: "Vento",
        year: 2021,
        vehicleType: "SEDAN",
        category: "PREMIUM",
        pricePerDay: 4900,
        seats: 5,
        bagCapacity: 2,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 25,
      },
      {
        imageUrl: "/t-cross.png",
        brand: "Volkswagen",
        model: "T-Cross",
        year: 2023,
        vehicleType: "SUV",
        category: "PREMIUM",
        pricePerDay: 6200,
        seats: 5,
        bagCapacity: 3,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 25,
      },
      {
        imageUrl: "/corolla-cross.png",
        brand: "Toyota",
        model: "Corolla Cross",
        year: 2024,
        vehicleType: "SUV",
        category: "PREMIUM",
        pricePerDay: 7100,
        seats: 5,
        bagCapacity: 3,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 25,
      },
      {
        imageUrl: "/ford-territory.png",
        brand: "Ford",
        model: "Territory",
        year: 2022,
        vehicleType: "SUV",
        category: "PREMIUM",
        pricePerDay: 6800,
        seats: 5,
        bagCapacity: 3,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 25,
      },
      {
        imageUrl: "/jeep-compass.png",
        brand: "Jeep",
        model: "Compass",
        year: 2023,
        vehicleType: "SUV",
        category: "LUXURY",
        pricePerDay: 11800,
        seats: 5,
        bagCapacity: 4,
        suitcaseCapacity: 3,
        gearbox: "AUTOMATIC",
        ageRequired: 30,
      },
      {
        imageUrl: "/audi-q5.png",
        brand: "Audi",
        model: "Q5",
        year: 2023,
        vehicleType: "SUV",
        category: "LUXURY",
        pricePerDay: 18900,
        seats: 5,
        bagCapacity: 4,
        suitcaseCapacity: 3,
        gearbox: "AUTOMATIC",
        ageRequired: 30,
      },
      {
        imageUrl: "/bmw_320i.png",
        brand: "BMW",
        model: "320i",
        year: 2023,
        vehicleType: "SEDAN",
        category: "LUXURY",
        pricePerDay: 15500,
        seats: 5,
        bagCapacity: 2,
        suitcaseCapacity: 2,
        gearbox: "AUTOMATIC",
        ageRequired: 30,
      },
      {
        imageUrl: "/chevrolet-spin.avif",
        brand: "Chevrolet",
        model: "Spin",
        year: 2021,
        vehicleType: "FAMILY_CAR",
        category: "ECONOMY",
        pricePerDay: 4200,
        seats: 7,
        bagCapacity: 3,
        suitcaseCapacity: 2,
        gearbox: "MANUAL",
        ageRequired: 25,
      },
      {
        imageUrl: "/citroen-berlingo.png",
        brand: "Citroën",
        model: "Berlingo",
        year: 2022,
        vehicleType: "FAMILY_CAR",
        category: "ECONOMY",
        pricePerDay: 4500,
        seats: 7,
        bagCapacity: 4,
        suitcaseCapacity: 3,
        gearbox: "MANUAL",
        ageRequired: 25,
      },
      {
        imageUrl: "/peugeot-308-sw.avif",
        brand: "Peugeot",
        model: "308 SW",
        year: 2023,
        vehicleType: "STATION_WAGON",
        category: "PREMIUM",
        pricePerDay: 5900,
        seats: 5,
        bagCapacity: 3,
        suitcaseCapacity: 3,
        gearbox: "AUTOMATIC",
        ageRequired: 25,
      },
    ],
  });

  console.log(`Seed completed: ${result.count} cars created`);

}

seedCars()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });


